'''Train a simple deep CNN on a HeLa dataset.
GPU run command:
	THEANO_FLAGS=mode=FAST_RUN,device=gpu,floatX=float32 python cifar10_cnn.py

'''

from __future__ import print_function
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten
from keras.layers import Convolution2D, MaxPooling2D
from keras.layers.normalization import BatchNormalization
from keras.callbacks import ModelCheckpoint, LearningRateScheduler
from keras.regularizers import l2
from keras.optimizers import SGD, RMSprop
from keras.utils import np_utils

from cnn_functions import get_data_sample, ImageDataGenerator, rate_scheduler
from model_zoo import bn_feature_net_multires_61x61

import os
import datetime
import numpy as np_

batch_size = 32
nb_classes = 3
nb_epoch = 200
data_augmentation = True

trained_network_directory = "/home/vanvalen/ImageAnalysis/DeepCell2/trained_networks/"
data_directory = "/home/vanvalen/ImageAnalysis/DeepCell2/training_data_npz/"
training_data_file_name = os.path.join(data_directory, "HeLa_set1_61x61.npz")

todays_date = datetime.datetime.now().strftime("%Y-%m-%d")
file_name_save = os.path.join(trained_network_directory, todays_date + "_HeLa_set1_bn_multires_61x61.h5")
file_name_save_loss = os.path.join(trained_network_directory, todays_date + "_HeLa_set1_bn_multires_61x61.npz")
train_dict, (X_test, Y_test) = get_data_sample(training_data_file_name)

# input image dimensions
img_rows, img_cols = 61, 61
img_channels = 2

# the data, shuffled and split between train and test sets
print('X_train shape:', train_dict["channels"].shape)
print(train_dict["pixels_x"].shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

# convert class vectors to binary class matrices
train_dict["labels"] = np_utils.to_categorical(train_dict["labels"], nb_classes)
Y_test = np_utils.to_categorical(Y_test, nb_classes)

model = bn_feature_net_multires_61x61(n_channels = 2, reg = 1e-5)

# let's train the model using SGD + momentum (how original).
sgd = SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

model.compile(loss='categorical_crossentropy',
			  optimizer=sgd,
			  metrics=['accuracy'])

print('Using real-time data augmentation.')

# this will do preprocessing and realtime data augmentation
datagen = ImageDataGenerator(
	rotate = True,  # randomly rotate images by 90 degrees
	shear_range = 0, # randomly shear images in the range (radians , -shear_range to shear_range)
	horizontal_flip=True,  # randomly flip images
	vertical_flip=True)  # randomly flip images

# fit the model on the batches generated by datagen.flow()
loss_history = model.fit_generator(datagen.sample_flow(train_dict, batch_size=batch_size),
					samples_per_epoch=len(train_dict["labels"]),
					nb_epoch=nb_epoch,
					validation_data=(X_test, Y_test),
					callbacks = [ModelCheckpoint(file_name_save, monitor = 'val_loss', verbose = 0, save_best_only = False, mode = 'auto'),
						LearningRateScheduler(rate_scheduler(lr = 0.01, decay = 0.95))])

model.save_weights(file_name_save)
np.savez(file_name_save_loss, loss_history = loss_history)